# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - main

resources:
- repo: self

variables:
  ContainerRegistry: '{"loginServer":"crtstcontainerregistry.azurecr.io", "id" : "/subscriptions/d35b6a23-881d-4b45-9836-652e55e255cb/resourceGroups/we-tst-container-registry/providers/Microsoft.ContainerRegistry/registries/crtstcontainerregistry"}'
  imageName: 'image-$(Build.Repository.Name):latest'

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildTST
  displayName: Build image & Deploy on TST
  jobs:
  - job: Build
    displayName: Build & Deploy
    steps:
    - task: Docker@0
      displayName: 'Build an image'
      inputs:
        azureSubscription: 'amilinovic_test (d35b6a23-881d-4b45-9836-652e55e255cb)'
        azureContainerRegistry: '$(ContainerRegistry)'
        dockerFile: Dockerfile
        imageName: 'image-$(Build.Repository.Name):tst'
    - task: Docker@0
      displayName: 'Push an image'
      inputs:
        azureSubscription: 'amilinovic_test (d35b6a23-881d-4b45-9836-652e55e255cb)'
        azureContainerRegistry: '$(ContainerRegistry)'
        action: 'Push an image'
        imageName: 'image-$(Build.Repository.Name):tst'

- stage: BuildACC
  displayName: Build image & Deploy on ACC
  jobs:
  - job: Build
    displayName: Build & Deploy
    steps:
    - task: Docker@0
      displayName: 'Build an image'
      inputs:
        azureSubscription: 'amilinovic_test (d35b6a23-881d-4b45-9836-652e55e255cb)'
        azureContainerRegistry: '$(ContainerRegistry)'
        dockerFile: Dockerfile
        imageName: 'image-$(Build.Repository.Name):acc'
    - task: Docker@0
      displayName: 'Push an image'
      inputs:
        azureSubscription: 'amilinovic_test (d35b6a23-881d-4b45-9836-652e55e255cb)'
        azureContainerRegistry: '$(ContainerRegistry)'
        action: 'Push an image'
        imageName: 'image-$(Build.Repository.Name):acc'

- stage: BuildPRD
  displayName: Build image & Deploy on PRD
  jobs:
  - job: Build
    displayName: Build & Deploy
    steps:
    - task: Docker@0
      displayName: 'Build an image'
      inputs:
        azureSubscription: 'amilinovic_test (d35b6a23-881d-4b45-9836-652e55e255cb)'
        azureContainerRegistry: '$(ContainerRegistry)'
        dockerFile: Dockerfile
        imageName: 'image-$(Build.Repository.Name):prd'
    - task: Docker@0
      displayName: 'Push an image'
      inputs:
        azureSubscription: 'amilinovic_test (d35b6a23-881d-4b45-9836-652e55e255cb)'
        azureContainerRegistry: '$(ContainerRegistry)'
        action: 'Push an image'
        imageName: 'image-$(Build.Repository.Name):prd'
    # - task: Docker@0
    #   displayName: 'Build an image'
    #   inputs:
    #     containerregistrytype: 'Azure Container Registry'
    #     azureSubscription: 'amilinovic_test'
    #     azureContainerRegistry: 'crwetsttestplaybook.azurecr.io'
    #     action: 'Build an image'
    #     dockerFile: 'Dockerfile'
    #     imageName: '$(imageName)'
    # - task: Docker@0
    #   displayName: 'Push an image'
    #   inputs:
    #     containerregistrytype: 'Azure Container Registry'
    #     azureSubscription: 'amilinovic_test'
    #     azureContainerRegistry: 'crwetsttestplaybook.azurecr.io'
    #     action: 'Push an image'
    #     imageName: '$(imageName)'